// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.Aggreement;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Aggreement_Roo_Configurable {
    
    declare @type: Aggreement: @Configurable;
    
}
