// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.Company;

privileged aspect Company_Roo_JavaBean {
    
    public String Company.getName() {
        return this.name;
    }
    
    public void Company.setName(String name) {
        this.name = name;
    }
    
}
