// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.Estimate;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Estimate_Roo_Configurable {
    
    declare @type: Estimate: @Configurable;
    
}
