// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.ItemName;

privileged aspect ItemName_Roo_JavaBean {
    
    public String ItemName.getName() {
        return this.name;
    }
    
    public void ItemName.setName(String name) {
        this.name = name;
    }
    
}
