// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.LabourSupplier;

privileged aspect LabourSupplier_Roo_JavaBean {
    
    public String LabourSupplier.getName() {
        return this.name;
    }
    
    public void LabourSupplier.setName(String name) {
        this.name = name;
    }
    
}
