// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.LabourEntry;
import javax.persistence.Entity;

privileged aspect LabourEntry_Roo_Jpa_Entity {
    
    declare @type: LabourEntry: @Entity;
    
}
