// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.ManagedDocument;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ManagedDocument_Roo_Configurable {
    
    declare @type: ManagedDocument: @Configurable;
    
}
