// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.org.entity;

import com.org.entity.MaterialEntry;
import javax.persistence.Entity;

privileged aspect MaterialEntry_Roo_Jpa_Entity {
    
    declare @type: MaterialEntry: @Entity;
    
}
