package com.org.excel.util;

public class ExtraItemRanges {
	public static String TABLE_EXTRA_ITEMS_ID = "TABLE_EXTRA_ITEMS_ID";
	public static String TABLE_EXTRA_ITEMS_VALID_ITEM_NUM = "TABLE_EXTRA_ITEMS_VALID_ITEM_NUM";
	public static String TABLE_EXTRA_ITEMS_ITEM_NUM = "TABLE_EXTRA_ITEMS_ITEM_NUM";
	public static String TABLE_EXTRA_ITEMS_DESC = "TABLE_EXTRA_ITEMS_DESC";
	public static String TABLE_EXTRA_ITEMS_QTY = "TABLE_EXTRA_ITEMS_QTY";
	public static String TABLE_EXTRA_ITEMS_UNIT = "TABLE_EXTRA_ITEMS_UNIT";
	public static String TABLE_EXTRA_ITEMS_QTY_PER_UNIT = "TABLE_EXTRA_ITEMS_QTY_PER_UNIT";
	public static String TABLE_EXTRA_ITEMS_DSR_RATE = "TABLE_EXTRA_ITEMS_DSR_RATE";
	public static String TABLE_EXTRA_ITEMS_FULL_RATE = "TABLE_EXTRA_ITEMS_FULL_RATE";
	public static String TABLE_EXTRA_ITEMS_PART_RATE = "TABLE_EXTRA_ITEMS_PART_RATE";
	public static String TABLE_EXTRA_ITEMS_DSR_CODE = "TABLE_EXTRA_ITEMS_DSR_CODE";
	public static String T_AGGREEMENT_ID = "T_AGGREEMENT_ID";
	public static String T_METADATA_EXISTING_ITEMS_IN_DATABASE = "EXISTING_ITEMS_IN_DATABASE";

}
